### ISSUE TITLE
Npm

### ISSUE THREAD

**Issue by Riders004** [j3lte/pastedeno#4]
How can I Upload This Module To My Npm Account For commonjs compatibility

**Comment by j3lte** [comment]
What do you mean "upload to your own npm account"? This module is both for Deno as well as Node, see README

**Comment by Riders004** [comment]
> What do you mean "upload to your own npm account"? This module is both for Deno as well as Node, see README

Actually it's giving error of esm module so I'm think to re upload that file I'm npm or GitHub with node-fetch version 2 so I'll ask how can I upload in my npm
